-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."adventWords"
(
    day smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    word character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "adventWords_pkey" PRIMARY KEY (day)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."adventWords"
    OWNER to postgres;

GRANT ALL ON TABLE public."adventWords" TO anon;

GRANT ALL ON TABLE public."adventWords" TO authenticated;

GRANT ALL ON TABLE public."adventWords" TO postgres;

GRANT ALL ON TABLE public."adventWords" TO service_role;
