-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.leaderboard
    ADD CONSTRAINT "leaderboard_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.users ("userId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
