-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: santaRegion

-- DROP TYPE IF EXISTS public."santaRegion";

CREATE TYPE public."santaRegion" AS ENUM
    ('na', 'eu', 'any');

ALTER TYPE public."santaRegion"
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public."santaLetters"
(
    "userId" character varying COLLATE pg_catalog."default" NOT NULL,
    region "santaRegion" NOT NULL,
    "postCount" integer NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    "matcheeId" character varying COLLATE pg_catalog."default",
    CONSTRAINT "santaLetters_pkey" PRIMARY KEY ("userId")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."santaLetters"
    OWNER to postgres;

GRANT ALL ON TABLE public."santaLetters" TO anon;

GRANT ALL ON TABLE public."santaLetters" TO authenticated;

GRANT ALL ON TABLE public."santaLetters" TO postgres;

GRANT ALL ON TABLE public."santaLetters" TO service_role;
